export const colors = {
  border: {
    DEFAULT: 'var(--color-border-1)',
    1: 'var(--color-border-1)',
    2: 'var(--color-border-2)',
    3: 'var(--color-border-3)',
  },
  bg: {
    DEFAULT: 'var(--color-bg-1)',
    /** 全局背景色 */
    1: 'var(--color-bg-1)',
    /** 一级容器背景色 */
    2: 'var(--color-bg-2)',
    /** 二级容器背景色 */
    3: 'var(--color-bg-3)',
    /** 三级容器背景色 */
    4: 'var(--color-bg-4)',
    /** 弹出层背景色 */
    5: 'var(--color-bg-5)',
  },
  text: {
    DEFAULT: 'var(--color-text-2)',
    1: 'var(--color-text-1)',
    2: 'var(--color-text-2)',
    3: 'var(--color-text-3)',
    4: 'var(--color-text-4)',
  },
  fill: {
    DEFAULT: 'var(--color-fill-1)',
    1: 'var(--color-fill-1)',
    2: 'var(--color-fill-2)',
    3: 'var(--color-fill-3)',
  },
  danger: {
    1: 'rgb(var(--danger-1))',
    2: 'rgb(var(--danger-2))',
    3: 'rgb(var(--danger-3))',
    4: 'rgb(var(--danger-4))',
    5: 'rgb(var(--danger-5))',
    6: 'rgb(var(--danger-6))',
    DEFAULT: 'rgb(var(--danger-6))',
    hover: 'rgb(var(--danger-5))',
    active: 'rgb(var(--danger-7))',
    disabled: 'rgb(var(--danger-3))',
    light: {
      1: 'var(--color-danger-light-1)',
      2: 'var(--color-danger-light-2)',
      3: 'var(--color-danger-light-3)',
      4: 'var(--color-danger-light-4)',
      DEFAULT: 'var(--color-danger-light-1)',
      hover: 'var(--color-danger-light-2)',
      active: 'var(--color-danger-light-3)',
    },
  },
  success: {
    1: 'rgb(var(--success-1))',
    2: 'rgb(var(--success-2))',
    3: 'rgb(var(--success-3))',
    4: 'rgb(var(--success-4))',
    5: 'rgb(var(--success-5))',
    6: 'rgb(var(--success-6))',
    DEFAULT: 'rgb(var(--success-6))',
    hover: 'rgb(var(--success-5))',
    active: 'rgb(var(--success-7))',
    disabled: 'rgb(var(--success-3))',
    light: {
      1: 'var(--color-success-light-1)',
      2: 'var(--color-success-light-2)',
      3: 'var(--color-success-light-3)',
      4: 'var(--color-success-light-4)',
      DEFAULT: 'var(--color-success-light-1)',
      hover: 'var(--color-success-light-2)',
      active: 'var(--color-success-light-3)',
    },
  },
  warning: {
    1: 'rgb(var(--warning-1))',
    2: 'rgb(var(--warning-2))',
    3: 'rgb(var(--warning-3))',
    4: 'rgb(var(--warning-4))',
    5: 'rgb(var(--warning-5))',
    6: 'rgb(var(--warning-6))',
    DEFAULT: 'rgb(var(--warning-6))',
    hover: 'rgb(var(--warning-5))',
    active: 'rgb(var(--warning-7))',
    disabled: 'rgb(var(--warning-3))',
    light: {
      DEFAULT: 'var(--color-warning-light-1)',
      1: 'var(--color-warning-light-1)',
      2: 'var(--color-warning-light-2)',
      3: 'var(--color-warning-light-3)',
      4: 'var(--color-warning-light-4)',
      hover: 'var(--color-warning-light-2)',
      active: 'var(--color-warning-light-3)',
    },
  },
  primary: {
    1: 'rgb(var(--primary-1))',
    2: 'rgb(var(--primary-2))',
    3: 'rgb(var(--primary-3))',
    4: 'rgb(var(--primary-4))',
    5: 'rgb(var(--primary-5))',
    6: 'rgb(var(--primary-6))',
    DEFAULT: 'rgb(var(--primary-6))',
    hover: 'rgb(var(--primary-5))',
    active: 'rgb(var(--primary-7))',
    disabled: 'rgb(var(--primary-3))',
    light: {
      1: 'var(--color-primary-light-1)',
      2: 'var(--color-primary-light-2)',
      3: 'var(--color-primary-light-3)',
      4: 'var(--color-primary-light-4)',
      DEFAULT: 'var(--color-primary-light-1)',
      hover: 'var(--color-primary-light-2)',
      active: 'var(--color-primary-light-3)',
    },
  },
  link: {
    1: 'rgb(var(--link-1))',
    2: 'rgb(var(--link-2))',
    3: 'rgb(var(--link-3))',
    4: 'rgb(var(--link-4))',
    5: 'rgb(var(--link-5))',
    6: 'rgb(var(--link-6))',
    DEFAULT: 'rgb(var(--link-6))',
    hover: 'rgb(var(--link-5))',
    active: 'rgb(var(--link-7))',
    disabled: 'rgb(var(--link-3))',
    light: {
      1: 'var(--color-link-light-1)',
      2: 'var(--color-link-light-2)',
      3: 'var(--color-link-light-3)',
      4: 'var(--color-link-light-4)',
      DEFAULT: 'var(--color-link-light-1)',
      hover: 'var(--color-link-light-2)',
      active: 'var(--color-link-light-3)',
    },
  },

  input: 'hsl(var(--input))',
  ring: 'hsl(var(--ring))',
  foreground: 'hsl(var(--foreground))',
  secondary: {
    DEFAULT: 'hsl(var(--secondary))',
    foreground: 'hsl(var(--secondary-foreground))',
  },
  destructive: {
    DEFAULT: 'hsl(var(--destructive))',
    foreground: 'hsl(var(--destructive-foreground))',
  },
  muted: {
    DEFAULT: 'hsl(var(--muted))',
    foreground: 'hsl(var(--muted-foreground))',
  },
  accent: {
    DEFAULT: 'hsl(var(--accent))',
    foreground: 'hsl(var(--accent-foreground))',
  },
  popover: {
    DEFAULT: 'hsl(var(--popover))',
    foreground: 'hsl(var(--popover-foreground))',
  },
  card: {
    DEFAULT: 'hsl(var(--card))',
    foreground: 'hsl(var(--card-foreground))',
  },
};
